# Generated by Django 4.2 on 2023-04-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingmodel',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postingmodel',
            name='thumbnail',
            field=models.TextField(default='../templates/img/thumbnail.png'),
        ),
    ]
