# Generated by Django 4.2 on 2023-04-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_alter_postingmodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingmodel',
            name='thumbnail',
            field=models.TextField(),
        ),
    ]
