# Generated by Django 4.2 on 2023-04-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_alter_postingmodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingmodel',
            name='thumbnail',
            field=models.TextField(default='https://cdn.lecturernews.com/news/photo/202011/56150_217126_754.jpg'),
        ),
    ]
