# Generated by Django 4.2 on 2023-04-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='favorite',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='mbti',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tmi',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='bio',
            field=models.CharField(default='', max_length=256),
        ),
    ]
