# Generated by Django 4.2 on 2023-04-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
